name: CI

on:
  push:
    branches: [ main, terraform ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: 'chenette'
          workload_identity_provider: 'projects/300512712029/locations/global/workloadIdentityPools/github/providers/my-repo'
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate -no-color
      
      # - name: Terraform Plan
      #   if: github.event_name == 'pull_request'
      #   run: terraform plan -no-color
      #   continue-on-error: true

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Show
        run: terraform show
